<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link rel="SHORTCUT ICON" href="/favicon.ico" />
	<style type="text/css" media="screen">
		@import url("/skins/default/skin.css");
	</style>
	<style type="text/css" media="print">@import url("/skins/default/print.css");</style>
	<script src="/functions.js" type="text/javascript"></script>
	<title>Receipt Tracking</title>
</head>
<body>
<div id="banner">
	<h1><a href="<?php echo BASE_URL; ?>">Receipt Tracking</a></h1><h2>Police Department</h2>
</div>
